FROM rafego16/pipeline-custom-image:latest
WORKDIR /app

# update env
COPY .env .env

# docker build -t rafego16/pipeline-custom-image:latest .
# docker rmi $(docker images -f "dangling=true" -q) --force
# docker push rafego16/pipeline-custom-image:latest
