apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: random-predictor
  namespace: test
spec:
  predictor:
    containers:
      - name: kserve-container
        image: rafego16/train-torch

# (errors) kubectl get inferenceservice random-predictor -n test -o yaml | grep -A 5 -m 1 message
# curl random-predictor.test.svc.cluster.local/v1/models/custom-model:predict -d '{"instances": [1, 2, 3]}'