apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: random-predictor
  namespace: test
spec:
  predictor:
    containers:
      - name: kserve-container
        image: rafego16/train-torch # registry.localhost/rl-agent-server:latest

# curl random-predictor.test.svc.cluster.local/v1/models/custom-model:predict -d '{"instances": [1, 2, 3]}'