FROM registry.localhost/pipeline-custom-image:latest
WORKDIR /app

# update env
COPY . .

# docker build -t registry.localhost/pipeline-custom-image:latest .
# docker rmi $(docker images -f "dangling=true" -q) --force
# docker push registry.localhost/pipeline-custom-image:latest
